import { app, BrowserWindow, ipcMain, dialog, shell, nativeTheme, Menu } from 'electron';
import { autoUpdater } from 'electron-updater';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs/promises';
import { existsSync } from 'node:fs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEV_URL = process.env.FOCUS_DEV_URL;

/** Occlusion detection on Windows can stall canvas repaints when the window is partly covered. */
app.commandLine.appendSwitch('disable-features', 'CalculateNativeWinOcclusion');
/** Keep the compositor running at the display refresh rate for low-latency inking. */
app.commandLine.appendSwitch('disable-frame-rate-limit');

const userDir = () => app.getPath('userData');
const boardsDir = () => path.join(userDir(), 'boards');
const settingsFile = () => path.join(userDir(), 'settings.json');

async function ensureDirs() {
  await fs.mkdir(boardsDir(), { recursive: true });
}

/** Board ids are generated by the renderer; never let one escape the boards directory. */
function boardPath(id: string) {
  if (!/^[A-Za-z0-9_-]{1,64}$/.test(id)) throw new Error(`Identifiant de tableau invalide: ${id}`);
  return path.join(boardsDir(), `${id}.focusboard.json`);
}

let mainWindow: BrowserWindow | null = null;

function createWindow() {
  const win = new BrowserWindow({
    width: 1440,
    height: 900,
    minWidth: 900,
    minHeight: 600,
    show: false,
    backgroundColor: '#101114',
    autoHideMenuBar: true,
    titleBarStyle: 'hidden',
    titleBarOverlay: { color: '#17181c', symbolColor: '#c9ccd4', height: 40 },
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
      spellcheck: true,
    },
  });

  win.once('ready-to-show', () => win.show());

  win.webContents.setWindowOpenHandler(({ url }) => {
    if (url.startsWith('http://') || url.startsWith('https://')) shell.openExternal(url);
    return { action: 'deny' };
  });

  if (DEV_URL) {
    win.loadURL(DEV_URL);
  } else {
    win.loadFile(path.join(__dirname, '..', 'dist', 'index.html'));
  }

  mainWindow = win;
  win.on('closed', () => {
    if (mainWindow === win) mainWindow = null;
  });
  return win;
}

function buildMenu() {
  const send = (channel: string, ...args: unknown[]) => mainWindow?.webContents.send(channel, ...args);
  const template: Electron.MenuItemConstructorOptions[] = [
    {
      label: 'Fichier',
      submenu: [
        { label: 'Nouveau tableau', accelerator: 'CmdOrCtrl+N', click: () => send('menu', 'board:new') },
        { label: 'Bibliothèque de tableaux', accelerator: 'CmdOrCtrl+O', click: () => send('menu', 'board:library') },
        { type: 'separator' },
        { label: 'Importer…', click: () => send('menu', 'board:import') },
        {
          label: 'Exporter',
          submenu: [
            { label: 'Image PNG…', accelerator: 'CmdOrCtrl+Shift+E', click: () => send('menu', 'export:png') },
            { label: 'Vectoriel SVG…', click: () => send('menu', 'export:svg') },
            { label: 'Fichier .focusboard…', click: () => send('menu', 'export:json') },
          ],
        },
        { type: 'separator' },
        { label: 'Quitter', role: 'quit' },
      ],
    },
    {
      label: 'Édition',
      submenu: [
        { label: 'Annuler', accelerator: 'CmdOrCtrl+Z', click: () => send('menu', 'edit:undo') },
        { label: 'Rétablir', accelerator: 'CmdOrCtrl+Shift+Z', click: () => send('menu', 'edit:redo') },
        { type: 'separator' },
        { label: 'Tout sélectionner', accelerator: 'CmdOrCtrl+A', click: () => send('menu', 'edit:selectAll') },
        { label: 'Supprimer la sélection', click: () => send('menu', 'edit:delete') },
        { type: 'separator' },
        { role: 'cut', label: 'Couper' },
        { role: 'copy', label: 'Copier' },
        { role: 'paste', label: 'Coller' },
      ],
    },
    {
      label: 'Affichage',
      submenu: [
        { label: 'Zoom avant', accelerator: 'CmdOrCtrl+Plus', click: () => send('menu', 'view:zoomIn') },
        { label: 'Zoom arrière', accelerator: 'CmdOrCtrl+-', click: () => send('menu', 'view:zoomOut') },
        { label: 'Taille réelle', accelerator: 'CmdOrCtrl+0', click: () => send('menu', 'view:zoomReset') },
        { label: 'Ajuster au contenu', accelerator: 'CmdOrCtrl+1', click: () => send('menu', 'view:zoomFit') },
        { type: 'separator' },
        { label: 'Thème clair / sombre', accelerator: 'CmdOrCtrl+D', click: () => send('menu', 'view:toggleTheme') },
        { label: 'Plein écran', role: 'togglefullscreen', accelerator: 'F11' },
        { type: 'separator' },
        { label: 'Outils de développement', role: 'toggleDevTools' },
      ],
    },
    {
      label: 'Aide',
      submenu: [
        { label: 'Raccourcis clavier', accelerator: 'F1', click: () => send('menu', 'help:shortcuts') },
        { label: 'Diagnostic tablette', click: () => send('menu', 'help:tablet') },
      ],
    },
  ];
  Menu.setApplicationMenu(Menu.buildFromTemplate(template));
}

/* ------------------------------------------------------------- auto-update */

/**
 * L'utilisateur choisit quand télécharger (popup « Installer »), pas
 * electron-updater tout seul en tâche de fond — on désactive donc le
 * téléchargement automatique et on pilote chaque étape depuis le renderer.
 *
 * Ne s'applique qu'à l'installation NSIS : l'exécutable portable n'a pas
 * d'emplacement fixe où electron-updater puisse remplacer les fichiers en
 * place, `app.isPackaged` seul ne suffit donc pas à l'écarter — on vérifie
 * aussi la présence du fichier de métadonnées que seul l'installeur pose.
 */
/** Cet exécutable a-t-il été lancé depuis l'exécutable portable ? */
function isPortableBuild(): boolean {
  // electron-builder pose cette variable d'environnement uniquement quand le
  // process a démarré depuis l'exe portable, quelle que soit sa position sur
  // le disque — c'est la seule façon fiable de le distinguer d'une installation.
  return Boolean(process.env.PORTABLE_EXECUTABLE_DIR);
}

const RECHECK_INTERVAL_MS = 30 * 60 * 1000;

function setupAutoUpdater() {
  autoUpdater.autoDownload = false;
  autoUpdater.autoInstallOnAppQuit = false;

  const send = (channel: string, ...args: unknown[]) => mainWindow?.webContents.send(channel, ...args);
  // Un nouveau sondage pendant qu'un téléchargement est en cours (ou prêt)
  // ne doit ni l'interrompre ni faire clignoter la carte côté renderer.
  let updateInFlight = false;

  autoUpdater.on('update-available', (info) => {
    updateInFlight = true;
    send('updater:available', { version: info.version, notes: typeof info.releaseNotes === 'string' ? info.releaseNotes : null });
  });
  autoUpdater.on('download-progress', (p) => {
    send('updater:progress', { percent: p.percent, bytesPerSecond: p.bytesPerSecond, transferred: p.transferred, total: p.total });
  });
  autoUpdater.on('update-downloaded', (info) => {
    send('updater:ready', { version: info.version });
  });
  autoUpdater.on('error', (err) => {
    send('updater:error', err.message);
  });

  ipcMain.handle('updater:download', async () => {
    await autoUpdater.downloadUpdate();
  });
  ipcMain.handle('updater:install', () => {
    autoUpdater.quitAndInstall();
  });

  const check = () => {
    if (updateInFlight) return;
    autoUpdater.checkForUpdates().catch((err) => {
      console.error('Vérification de mise à jour impossible :', err);
    });
  };

  // Différé pour ne jamais retarder l'affichage de la fenêtre au démarrage ;
  // une absence de réseau ne doit provoquer ni popup ni blocage, juste un
  // échec silencieux côté console. Puis un sondage périodique : l'app tourne
  // souvent des heures d'affilée, elle ne doit pas dépendre d'un redémarrage
  // pour remarquer une nouvelle release.
  setTimeout(check, 2500);
  setInterval(check, RECHECK_INTERVAL_MS);
}

/* ------------------------------------------------------------------ IPC */

ipcMain.handle('boards:list', async () => {
  await ensureDirs();
  const files = await fs.readdir(boardsDir());
  const out: unknown[] = [];
  for (const f of files) {
    if (!f.endsWith('.focusboard.json')) continue;
    try {
      const raw = await fs.readFile(path.join(boardsDir(), f), 'utf8');
      const doc = JSON.parse(raw);
      out.push({
        id: doc.id,
        name: doc.name ?? 'Sans titre',
        updatedAt: doc.updatedAt ?? 0,
        createdAt: doc.createdAt ?? 0,
        thumbnail: doc.thumbnail ?? null,
        elementCount: Array.isArray(doc.elements) ? doc.elements.length : 0,
      });
    } catch {
      /* fichier corrompu : on l'ignore plutôt que de casser la bibliothèque */
    }
  }
  return out;
});

ipcMain.handle('boards:read', async (_e, id: string) => {
  const p = boardPath(id);
  if (!existsSync(p)) return null;
  return JSON.parse(await fs.readFile(p, 'utf8'));
});

ipcMain.handle('boards:write', async (_e, doc: { id: string }) => {
  await ensureDirs();
  const p = boardPath(doc.id);
  // Écriture atomique : un crash pendant l'autosave ne doit pas détruire le tableau.
  const tmp = `${p}.tmp`;
  await fs.writeFile(tmp, JSON.stringify(doc), 'utf8');
  await fs.rename(tmp, p);
  return true;
});

ipcMain.handle('boards:delete', async (_e, id: string) => {
  const p = boardPath(id);
  if (existsSync(p)) await fs.unlink(p);
  return true;
});

ipcMain.handle('boards:reveal', async () => {
  await ensureDirs();
  shell.openPath(boardsDir());
  return boardsDir();
});

ipcMain.handle('settings:read', async () => {
  try {
    return JSON.parse(await fs.readFile(settingsFile(), 'utf8'));
  } catch {
    return {};
  }
});

ipcMain.handle('settings:write', async (_e, settings: unknown) => {
  await fs.mkdir(userDir(), { recursive: true });
  await fs.writeFile(settingsFile(), JSON.stringify(settings, null, 2), 'utf8');
  return true;
});

ipcMain.handle(
  'file:save',
  async (_e, args: { defaultName: string; data: string; encoding: 'utf8' | 'base64'; filters: Electron.FileFilter[] }) => {
    const res = await dialog.showSaveDialog(mainWindow!, {
      defaultPath: args.defaultName,
      filters: args.filters,
    });
    if (res.canceled || !res.filePath) return null;
    await fs.writeFile(res.filePath, Buffer.from(args.data, args.encoding));
    return res.filePath;
  },
);

ipcMain.handle('file:open', async (_e, filters: Electron.FileFilter[]) => {
  const res = await dialog.showOpenDialog(mainWindow!, { properties: ['openFile'], filters });
  if (res.canceled || !res.filePaths[0]) return null;
  return { path: res.filePaths[0], content: await fs.readFile(res.filePaths[0], 'utf8') };
});

ipcMain.handle('shell:showItem', async (_e, filePath: string) => {
  shell.showItemInFolder(filePath);
});

ipcMain.on('theme:set', (_e, theme: 'light' | 'dark') => {
  nativeTheme.themeSource = theme;
  mainWindow?.setTitleBarOverlay?.(
    theme === 'dark'
      ? { color: '#17181c', symbolColor: '#c9ccd4', height: 40 }
      : { color: '#f4f5f7', symbolColor: '#3a3d45', height: 40 },
  );
});

/* ----------------------------------------------------------------- boot */

app.whenReady().then(async () => {
  await ensureDirs();
  buildMenu();
  createWindow();
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
  // En dev, il n'y a ni build publié ni fichier de métadonnées à lire ; et le
  // portable n'a pas d'emplacement fixe où s'installer par-dessus lui-même.
  if (app.isPackaged && !isPortableBuild()) setupAutoUpdater();
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});
